version: '3'

services:
  # --- Service used for local development
  local-dev:
    # Building the local image
    build:
      context: ../
      dockerfile: ./Dockerfile
    # Running the local image
    image: "cicero-synthesizer-local-dev"
    container_name: "cicero-synthesizer-local-dev"
    environment:
      DOCKER_BUILDKIT_VALUE: ${DOCKER_BUILDKIT_VALUE}
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/opt/program
    working_dir: /opt/program
    command: [ "/bin/sleep", "365d" ]
  #
  # --- Service for running the API locally
  api:
    # Building the local image
    build:
      context: ../
      dockerfile: ./Dockerfile
    # Running the local image
    image: "cicero-synthesizer-api"
    container_name: "cicero-synthesizer-api"
    environment:
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      HUGGING_FACE_USERNAME: ${HUGGING_FACE_USERNAME}
    volumes:
      - ..:/opt/ml
    ports:
      - ${INPUT_APP_PORT:-8501}:${OUTPUT_APP_PORT:-8501}
    working_dir: /opt/ml
    command:
      [
        "uvicorn",
        "src.api.index:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8501",
        "--reload",
        "--reload-dir",
        "/opt/ml"
      ]
  #
  # --- Service for running the Gradio application locally
  app:
    # Building the local image
    build:
      context: ../
      dockerfile: ./Dockerfile
    # Running the local image
    image: "cicero-synthesizer-app"
    container_name: "cicero-synthesizer-app"
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
      HUGGING_FACE_USERNAME: ${HUGGING_FACE_USERNAME}
    volumes:
      - ..:/opt/ml
    ports:
      - ${APP_SERVER_PORT:-7860}:${APP_SERVER_PORT:-7860}
    working_dir: /opt/ml
    command: [ "python", "src/app_service/app.py" ]
